# python3 optimization/run_optimization_comprehensive.py --lambda_similarity 0.002 --lambda_identity 0.0 --truncation 0.7 --lr 0.1 --audio_path "/mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/data/test.wav" --ckpt ./pretrained_models/landscape.pt  --stylegan_size 512 --emotion "positive"
python3 optimization/run_optimization_comprehensive.py --lambda_similarity 0.002 --lambda_identity 0.000 --truncation 0.7 --lr 0.1 --audio_path "/mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/audiosample/fire.wav" --ckpt ./pretrained_models/landscape.pt  --stylegan_size 512 --emotion "positive" --results_dir /mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/Experience/Semantic/fire  --description "fire"
python3 optimization/StyleCLIP.py --lambda_similarity 0.002 --lambda_identity 0.000 --truncation 0.7 --lr 0.1 --audio_path "/mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/audiosample/fire.wav" --ckpt ./pretrained_models/landscape.pt  --stylegan_size 512 --emotion "positive" --results_dir /mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/Experience/Semantic/fire  --description "fire" 
python3 optimization/Lee.py --lambda_similarity 0.002 --lambda_identity 0.000 --truncation 0.7 --lr 0.1 --audio_path "/mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/audiosample/fire.wav" --ckpt ./pretrained_models/landscape.pt  --stylegan_size 512 --emotion "positive" --results_dir /mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/Experience/Semantic/fire  --description "fire"
python3 optimization/run_optimization_wo_music.py --lambda_similarity 0.002 --lambda_identity 0.000 --truncation 0.7 --lr 0.1 --audio_path "/mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/audiosample/fire.wav" --ckpt ./pretrained_models/landscape.pt  --stylegan_size 512 --emotion "positive" --results_dir /mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/Experience/Semantic/fire  --description "fire"
python3 optimization/run_optimization_wo_audio.py --lambda_similarity 0.002 --lambda_identity 0.000 --truncation 0.7 --lr 0.1 --audio_path "/mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/audiosample/fire.wav" --ckpt ./pretrained_models/landscape.pt  --stylegan_size 512 --emotion "positive" --results_dir /mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/Experience/Semantic/fire  --description "fire"
python3 optimization/run_optimization_wo_text.py --lambda_similarity 0.002 --lambda_identity 0.000 --truncation 0.7 --lr 0.1 --audio_path "/mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/audiosample/fire.wav" --ckpt ./pretrained_models/landscape.pt  --stylegan_size 512 --emotion "positive" --results_dir /mnt/ssd/BeautifulXJJ/AIGC/Sound-Image-Generation/sound-guided-semantic-image-manipulation/Experience/Semantic/fire  --description "fire"

# rain falling from the sky
